# GitHub Actions Workflow for pkgdown deployment

on:
  push:
    branches: [main, master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions:
  contents: write
  pages: write  # Required for GitHub Pages deployment
  id-token: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Install dependencies manually
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "pkgdown"))
          remotes::install_github("redivis/redivis-r", ref="main")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      # Install irwpkg before building site
      - name: Install irwpkg before building site
        run: |
          remotes::install_local(dependencies = TRUE)
        shell: Rscript {0}

      # Build the site
      - name: Build site
        run: pkgdown::build_site()
        shell: Rscript {0}

      # Upload `docs/` as an artifact for GitHub Pages deployment
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs  # This is where pkgdown generates the website

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        uses: actions/deploy-pages@v2