# # Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# on:
#   push:
#     branches: [main, master]
#   pull_request:
# 
# name: R-CMD-check.yaml
# 
# permissions: read-all
# 
# jobs:
#   R-CMD-check:
#     runs-on: ${{ matrix.config.os }}
# 
#     name: ${{ matrix.config.os }} (${{ matrix.config.r }})
# 
#     strategy:
#       fail-fast: false
#       matrix:
#         config:
#           - {os: macos-latest,   r: 'release'}
#           - {os: windows-latest, r: 'release'}
#           - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
#           - {os: ubuntu-latest,   r: 'release'}
#           - {os: ubuntu-latest,   r: 'oldrel-1'}
# 
#     env:
#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
#       R_KEEP_PKG_SOURCE: yes
# 
#     steps:
#       # Step 1: Checkout the code
#       - uses: actions/checkout@v4
# 
#       # Step 2: Setup Pandoc
#       - uses: r-lib/actions/setup-pandoc@v2
# 
#       # Step 3: Setup R environment
#       - uses: r-lib/actions/setup-r@v2
#         with:
#           r-version: ${{ matrix.config.r }}
#           http-user-agent: ${{ matrix.config.http-user-agent }}
#           use-public-rspm: true
# 
#       # Step 4: Install remotes
#       # Install the `remotes` package for GitHub package installation
#       - name: Install remotes
#         run: |
#           Rscript -e 'if (!requireNamespace("remotes", quietly = TRUE)) install.packages("remotes")'
# 
#       # Step 5: Install Non-CRAN Dependency (redivis)
#       # Install the `redivis` package manually from GitHub
#       - name: Install redivis
#         run: |
#           Rscript -e 'remotes::install_github("redivis/redivis-r", ref = "main")'
# 
#       # Step 6: Install R package dependencies
#       - uses: r-lib/actions/setup-r-dependencies@v2
#         with:
#           extra-packages: any::rcmdcheck
#           needs: check
# 
#       # Step 7: Run R CMD Check
#       - uses: r-lib/actions/check-r-package@v2
#         with:
#           upload-snapshots: true
#           build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'